Add AuthTests class
YummyMirror/git_temp3 pull request #2
Opened 2021-03-29 17:53 UTC by YummyMirror

2021-03-29 17:55 UTC, YU-alt-acc requested changes

2021-03-29 17:55 UTC, YU-alt-acc commented on src/test/java/com/practice/git/test/AuthTests.java
> +    }
Why did you not create a BaseTest class and put fixtures into it?

2021-03-29 17:55 UTC, YU-alt-acc commented on src/test/java/com/practice/git/test/AuthTests.java
> +    }
The same as with BeforeClass

2021-03-29 17:55 UTC, YU-alt-acc commented on src/test/java/com/practice/git/test/AuthTests.java
> +        Navigator navigator = new Navigator(this.driver);
No lazy initialization

2021-03-30 06:20 UTC, YU-alt-acc requested changes

2021-03-30 06:20 UTC, YU-alt-acc commented on src/test/java/com/practice/git/application/ApplicationManager.java
> +    }
Why are they not thread safety?

2021-03-30 06:24 UTC, YummyMirror commented on src/test/java/com/practice/git/application/ApplicationManager.java
> +    }
It will be added later

2021-03-30 06:26 UTC, merged